name: ffmpeg-wasm build

on:
  push:
    branches: [master]
    # tags: ['v*']
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v6
        with:
          repository: ffmpegwasm/ffmpeg.wasm
          ref: v12.15

      - uses: actions/checkout@v6
        with:
          path: override

      - name: Update pkg-config database
        run: sudo ldconfig

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v4.1.0

      - name: Cache build
        id: cache-build
        uses: actions/cache@v5
        with:
          path: build-cache-st
          key: build-cache-st-v1-${{ hashFiles('Dockerfile', 'Makefile', 'build/*', 'override/src/*') }}
          restore-keys: |
            build-cache-st-v1-

      - name: Build FFmpeg
        run: |
          cp override/src/Dockerfile Dockerfile
          make prd EXTRA_ARGS="--cache-from=type=local,src=build-cache-st --cache-to=type=local,dest=build-cache-st,mode=max"

      - run: |
          ls -lRh packages/core/dist/

      - name: Upload core
        uses: actions/upload-artifact@v7
        with:
          name: ffmpeg-core
          path: packages/core/dist/*
          retention-days: 7

      # - name: Release
      #   if: startsWith(github.ref, 'refs/tags/')
      #   uses: softprops/action-gh-release@v3
      #   with:
      #     files: packages/core/dist/*
      #     generate_release_notes: true

  test:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v8
        with:
          name: ffmpeg-core
          path: packages/core/dist

      - uses: actions/setup-node@v6
        with:
          node-version-file: "test/.nvmrc"

      - run: |
          npm ci
          CHROMIUM_BIN=$(which microsoft-edge) node test.mjs
        working-directory: test

      - uses: actions/upload-artifact@v7
        with:
          name: ffmpeg-log
          path: test/log.txt
          retention-days: 7
